name: Pathogen repo build

on: workflow_dispatch

jobs:
  run-build:
    # These permissions are required for this workflow.
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
