name: CI

on:
  push:
    branches:
      - $default-branch
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    # These permissions are required for this workflow.
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-ci.yaml@master
