#!/bin/bash
# usage: write-envdir <envdir> [[var1 [var2 [var3 […]]]]
#
# Writes the current value for each environment variable name given into the
# directory <envdir>, one file per variable.  Creates <envdir> if it doesn't
# already exist.
#
# Originally written by @tsibley, copied unmodified from the ncov-ingest repo:
# https://github.com/nextstrain/ncov-ingest/blob/2a8f5bb4419998d5e3e13c97ebd03a1780ea47c2/bin/write-envdir
#
set -eou pipefail

dir="${1:?no envdir path}"
shift

mkdir -pv "$dir"
cd "$dir"

for name in "$@"; do
    echo "${!name}" > "$name"
    echo "Wrote $dir/$name"
done
